name: WakaTime Readme

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: all_time
          SHOW_TIME: true
